development: &default
  adapter: postgresql
  database: i-dream-i-dare_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  username: postgres
  password: root@123
  host: localhost

test:
  <<: *default
  database: i-dream-i-dare_test
  username: postgres
  password: root@123

production: &deploy
  adapter: postgresql
  database: i-dream-i-dare_development
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
  username: postgres 
  password: root@123
staging: *deploy
